name: trivy
on:
  push:
    branches:
    - main
    - staging
  pull_request:
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run Trivy vulnerability scanner in fs mode
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: fs
        scan-ref: '.'
        output: trivy-results.txt

    - name: Publish Trivy Output to Summary
      run: |
        if [[ -s trivy-results.txt ]]; then
          {
            echo "### Security Output"
            echo "<details><summary>Click to expand</summary>"
            echo ""
            echo '```terraform'
            cat trivy-results.txt
            echo '```'
            echo "</details>"
          } >> $GITHUB_STEP_SUMMARY
        fi

    - name: Parse Trivy results and push to Prometheus
      env:
        REPO_NAME: ${{ github.repository }}
      run: |
        set -e

        # Initialize counts to zero
        high_count=0
        critical_count=0
        medium_count=0

        if [[ -f trivy-results.txt && -s trivy-results.txt ]]; then
          # Extract the counts from the 'Total' line
          total_line=$(grep 'Total:' trivy-results.txt)
          high_count=$(echo "$total_line" | grep -oP 'HIGH: \K\d+')
          critical_count=$(echo "$total_line" | grep -oP 'CRITICAL: \K\d+')
          medium_count=$(echo "$total_line" | grep -oP 'MEDIUM: \K\d+')
        fi

        repo_name="${REPO_NAME}"

        cat <<EOF | curl --data-binary @- http://143.47.187.120:9091/metrics/job/github_actions
        github_actions_high_vulnerabilities{repo="$repo_name"} $high_count
        github_actions_critical_vulnerabilities{repo="$repo_name"} $critical_count
        github_actions_medium_vulnerabilities{repo="$repo_name"} $medium_count
        EOF
