name: trivy
on:
  push:
    branches:
    - main
    - staging
  pull_request:
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run Trivy vulnerability scanner in fs mode
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: fs
        scan-ref: '.'
        format: json
        output: trivy-results.json

    - name: Parse Trivy results and push to Prometheus
      run: |
        high_count=$(jq '[.Results[].Vulnerabilities[] | select(.Severity=="HIGH")] | length' trivy-results.json)
        critical_count=$(jq '[.Results[].Vulnerabilities[] | select(.Severity=="CRITICAL")] | length' trivy-results.json)

        echo "High vulnerabilities: $high_count"
        echo "Critical vulnerabilities: $critical_count"

        cat <<EOF | curl --data-binary @- http://143.47.187.120:9091/metrics/job/github_actions
        # TYPE github_actions_high_vulnerabilities gauge
        github_actions_high_vulnerabilities $high_count
        # TYPE github_actions_critical_vulnerabilities gauge
        github_actions_critical_vulnerabilities $critical_count
        EOF
