name: trivy
on:
  push:
    branches:
    - main
    - staging
  pull_request:
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run Trivy vulnerability scanner in fs mode
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: fs
        scan-ref: '.'
        output: trivy-results.txt

    - name: Publish Trivy Output to Summary
      run: |
        if [[ -s trivy-results.txt ]]; then
          {
            echo "### Security Output"
            echo "<details><summary>Click to expand</summary>"
            echo ""
            echo '```terraform'
            cat trivy-results.txt
            echo '```'
            echo "</details>"
          } >> $GITHUB_STEP_SUMMARY
        fi

    - name: Parse Trivy results and push to Prometheus
      run: |

        high_count=$(grep -c 'HIGH' trivy-results.txt || echo 0)
        critical_count=$(grep -c 'CRITICAL' trivy-results.txt || echo 0)

        cat <<EOF | curl --data-binary @- http://143.47.187.120:9091/metrics/job/github_actions
        github_actions_high_vulnerabilities $high_count
        github_actions_critical_vulnerabilities $critical_count
        EOF
